### ISSUE TITLE
Whitespace control outputs additionalProps without trailing space

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/snipcart#44]
Adding the option `additionalProps` outputs them without trailing space:
![Screenshot 2022-03-24 at 11 06 48](https://user-images.githubusercontent.com/1942313/159892827-31da8404-c25d-45c9-a6e1-6fdac97c000c.png)

I believe the issue is here:
https://github.com/FosterCommerce/snipcart-craft-plugin/blob/de517a75458a61b83970eba0d48bc3c3ca102454/src/templates/fields/front-end/buy-now.twig#L40

Need to replace with 
`{% endfor %}`

**Comment by sjcallender** [comment]
https://github.com/FosterCommerce/snipcart-craft-plugin/issues/55

**Comment by engram-design** [comment]
We'll likely completely replace this manual output with HTML helpers that'll fix this.

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/snipcart/releases/tag/2.1.0)
